name: 247_Cloud_Traffic_Farmer
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  surf_credits:
    runs-on: ubuntu-latest
    steps:
      - name: Download Official App Engine
        run: |
          # Downloads the exact Linux engine binary archive package directly
          wget https://otohits.net -O setup.tar.gz
          tar -xzf setup.tar.gz
          
      - name: Launch 247 Cloud Farming Loop
        run: |
          # Enters the app folder and initializes the software via your application key link
          cd OtohitsApp
          ./OtohitsApp --login:a9e28065-a17e-4fe4-98d3-26824dd962ed --nolog &
          echo "Official background engine launched! Farming credits into your balance..."
          sleep 2400
